[build]
## Netlify Lambda Build and Publishing
# This will be run the site build
command = "npm run build"
# This is the directory is publishing to netlify's CDN
publish = "public"
# Location of built function code
functions = "lambdas-built"

[dev]
  command = "npm run build" # Command to start your dev server
  port = 9000 # Port that the dev server will be accessible on
  publish = "public" # If you use a _redirect file, provide the path to your static content folder
  functions = "lambdas-built"

[dev.environment]
GH_CLIENT_APP_ID='1285225'
GH_CLIENT_ID='76ce40eaa5718c5271cf'
GH_CLIENT_SECRET='b113b5ac57eb0dbaf57501a6a301b3ac62474ba2'
GH_AUTH_URI='http://localhost:8000/.netlify/lambdas/auth'
GH_REDIRECT_URI='http://localhost:8000/.netlify/lambdas/auth-callback'

[build.environment]
GH_CLIENT_APP_ID='1280686'
GH_CLIENT_ID='963d366d593be476d2d1'
GH_CLIENT_SECRET='f953906547672cdb59204e6499d8089106ced79e'
GH_AUTH_URI='https://strivve-docs-8b1ae.netlify.app/.netlify/functions/auth'
GH_REDIRECT_URI='https://strivve-docs-8b1ae.netlify.app/.netlify/functions/auth'
API_URI=''

# Stackbit
#command = "./stackbit-build.sh"